apiVersion: v1
kind: Pod
metadata:
    name: app1
    labels:
        tier: frontend
        team: fteam
    annotations:
        myapp.io/version.ref: "1.0.0"
spec:
    containers:
        - image: nginx:1.25.3
          name: nginx

---
apiVersion: v1
kind: Pod
metadata:
    name: app2
    labels:
        tier: backend
        team: bteam
    annotations:
        myapp.io/version.ref: "1.1.2"
spec:
    containers:
        - image: nginx:1.25.3
          name: nginx