apiVersion: v1
kind: Namespace
metadata:
    name: web

---
apiVersion: v1
kind: Namespace
metadata:
    name: admin

---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    namespace: web
spec:
    type: ClusterIP
    selector:
        app: nginx-pod
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    namespace: web
    labels:
        app: nginx-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx-pod
    template:
        metadata:
            labels:
                app: nginx-pod
        spec:
            containers:
                - image: nginx:1.25.3
                  name: nginx
                  ports:
                      - containerPort: 80
                        name: http
---
apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-pod
    namespace: admin
spec:
    containers:
        - name: ubuntu-container
          image: ubuntu:latest
          command: ["/bin/bash", "-c"]
          args:
              - apt-get update && apt-get install -y curl && /bin/sleep infinity