apiVersion: v1
kind: ConfigMap
metadata:
    name: config
data:
    FIRST_VARIABLE: "test1"
    SECOND_VARIABLE: "test2"

---

apiVersion: v1
kind: Pod
metadata:
    name: nginx-app
spec:
    containers:
        - name: nginx-app
          image: nginx:1.25.3
          env:
              - name: APP_NAME
                value: nginx-app
              - name: APP_OS_VERSION
                value: "1.25.3"
              - name: FIRST_TEST_VARIABLE
                valueFrom:
                    configMapKeyRef:
                        name: config
                        key: FIRST_VARIABLE
              - name: SECOND_TEST_VARIABLE
                valueFrom:
                    configMapKeyRef:
                        name: config
                        key: SECOND_VARIABLE
